name: Java CI with Maven on Ubuntu

# Trigger the workflow on push to the master branch or when a pull request is opened
on:
  push:
    branches:
      - master  # Use master instead of main
  pull_request:
    branches:
      - master  # Run the workflow on pull requests to the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run on the Ubuntu runner provided by GitHub

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3 to avoid deprecation warnings

    - name: Set up JDK 11
      uses: actions/setup-java@v3  # Updated to v3 to avoid deprecation warnings
      with:
        distribution: 'adopt'  # Choose a Java distribution (adopt, temurin, zulu, etc.)
        java-version: '11'     # Specify the Java version (use 11 or adjust as needed)

    - name: Build with Maven
      run: mvn clean install  # Build the project with Maven

    - name: Run tests
      run: mvn test  # Run tests using Maven
